### PR TITLE
update version to release for 0.0.5

### PR DESCRIPTION
**Pull request by gurudatta-carbon**

### CODE REVIEW

**Review by micha-carbon — APPROVED** [review]
maybe just make it `0.0.6` ? idk if that matters. your call

**Comment by gurudatta-carbon** [comment]
> maybe just make it `0.0.6` ? idk if that matters. your call

0.0.5 should be fine, since no code changes from SNAPSHOT to release version of 0.0.5

**Comment by dboreham** [comment]
I'm not sure of the context here, do we want to also to this? https://github.com/mdcollab/fhirproto/compare/dboreham/upgrade-scala-2-12-14

**Comment by gurudatta-carbon** [comment]
> I'm not sure of the context here, do we want to also to this? https://github.com/mdcollab/fhirproto/compare/dboreham/upgrade-scala-2-12-14

updated PR description,
I think we should deal that separately to upgrade-scala-2-12-14

**Pull request merged**
